version: '3.8'

services:
  kiii-db:
    image: postgres:15
    container_name: songs_db
    environment:
      POSTGRES_USER: kiii
      POSTGRES_PASSWORD: kiii123
      POSTGRES_DB: kiii
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: songs-library-backend:latest
    container_name: songs
    depends_on:
      - kiii-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://kiii-db:5432/kiii
      SPRING_DATASOURCE_USERNAME: kiii
      SPRING_DATASOURCE_PASSWORD: kiii123

volumes:
  pgdata: