apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: namespace-songs
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://kiii-db:5432/kiii"
  SPRING_DATASOURCE_USERNAME: "kiii"
  SPRING_DATASOURCE_PASSWORD: "kiii123"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: namespace-songs
type: Opaque
data:
  POSTGRES_USER: a2lpaQ==
  POSTGRES_PASSWORD: a2lpaTEyMw==
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: namespace-songs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: krstevskidarko/songs-library-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
      imagePullSecrets:
        - name: app-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-db
  namespace: namespace-songs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiii-db
  template:
    metadata:
      labels:
        app: kiii-db
    spec:
      containers:
        - name: kiii-db
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "kiii"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          emptyDir: {}